### PR TITLE
some extra instructions for tags, finding the IDs, and pos/quat conversion

### PR DESCRIPTION
**Pull request by rennis250**

### CODE REVIEW

**Review by domstoppable — CHANGES_REQUESTED** [review]
The note about subtracting 90 degrees isn't correct. Explained:

> Start a file with three cubes. You can move them, but do not rotate them.
> * In the first cube, delete all but the left face
> * In the second cube, delete all but the front face
> * In the third cube, delete all but the top face
> 
> Each of these cubes are now simple planes, and each of these planes are planar with distinct global planes, but if you examine the rotation of each of these three objects, you'll see that they all have the same orientation.
> 
> Subtracting 90 degrees from the x-axis of the rotation will yield the correct results for one of these objects, but not for the other two.

FWIW, I have already added a line to the [readme](https://github.com/pupil-labs/tag-aligner/blob/14b20420c36faed75713f0395fcb8fbbc3a565bd/README.md?plain=1#L26) to help clarify the "correct" "default" orientation.

**Comment by rennis250** [comment]
Ah, interesting! I see. I missed your clarifier about "correct default" orientation.

Hmm.. okay, then if removing my blurb about the 90 degrees part, is it okay to add a short part to the "correct orientation" line that says something like "this corresponds to rotating a default Plane mesh in Blender by 90 degrees about the x-axis". I had written that blurb with a Plane mesh in mind, as that is what I used to represent my AprilTag in the scene.

It's just that this is the part that mainly tripped me up and knowing me, I would have still struggled a bit to understand why when my AprilTag plane is vertical and I do the Blender<->OpenCV conversion, we still have differences in our values.

**Comment by domstoppable** [comment]
> is it okay to add a short part to the "correct orientation" line that says something like "this corresponds to rotating a default Plane mesh in Blender by 90 degrees about the x-axis".

I think it'd be preferable to leave the blender-specific stuff out of the usage section. I'd be fine with it in the notes though

**Comment by rennis250** [comment]
I updated the changes based on our discussion

**Review by domstoppable — APPROVED** [review]

**Pull request merged**
